# Generated by Django 4.1 on 2022-09-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryPretty',
        ),
    ]
