# Generated by Django 4.1 on 2022-09-09 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_inventorypretty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='invent',
            field=models.ForeignKey(db_column='invent', on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='main.inventory'),
        ),
    ]
